spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bridge?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

server:
  port: 80